# Generated by Django 4.2.7 on 2025-01-28 15:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("refunded", "Refunded"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="stripe_payment_intent",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="base_price",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("350.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="cleaning_fee",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("150.00"), max_digits=10
            ),
        ),
    ]
